apiVersion: v1
kind: Secret
metadata:
  name: database-secret
data:
  DATABASE_USERNAME: SOME_BASE64_OR_OPAQUE # Base64-encoded username
  DATABASE_PASSWORD: SOME_BASE64_OR_OPAQUE # Base64-encoded password
